<a href="https://colab.research.google.com/github/Swathi04705/Applied-Machine-Learning-Lab/blob/main/applied_ML_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import scipy
print('scipy: %s' % scipy.__version__)

scipy: 1.16.3

In [ ]:
import numpy
print('numpy: %s' % numpy.__version__)

numpy: 2.0.2

In [ ]:
import pandas
print('pandas: %s' % pandas.__version__)

pandas: 2.2.3

In [ ]:
import statsmodels
print('statsmodels: %s' % statsmodels.__version__)

statsmodels: 0.14.6

In [ ]:
#scikit-learn
import sklearn
print('sklearn: %s' % sklearn.__version__)

sklearn: 1.6.1

BASICS

In [ ]:
def add(x,y):
  return x + y

In [ ]:
a = 44;
b = 6;
add(a,b)

50

In [ ]:
def add(x,y,z=None):
  if (z==None):
    return x + y
  else:
    return x + y + z

In [ ]:
print(add(22,8))

30

In [ ]:
print(add(4,4,8))

16

In [ ]:
def add(x,y,z=None, flag = False):
  if(flag):
    print('flag is on!')
  if(z==None):
    return x + y
  else:
    return x + y + z

In [ ]:
print(add(4,8,6))

18

In [ ]:
a = add
a(16,4)

20

TYPES

In [ ]:
type('p')

str

In [ ]:
type(None) #null value or abscence of value, empty placeholder

NoneType

In [ ]:
type(0)

int

In [ ]:
b = 36.4
type(b)

float

In [ ]:
type(add)

function

In [ ]:
x = (1,2,3)
print(x)

(1, 2, 3)

In [ ]:
x.append(4)
print(x)

AttributeError: 'tuple' object has no attribute 'append'

LISTS

In [ ]:
y = [1,2,3]
print(y)

In [ ]:
y.append('numbers')
print(y)

In [ ]:
for item in y:
  print(item)

In [ ]:
list1 = [1,2,3,4]
print(list1)

In [ ]:
print(list1 * 3)

In [ ]:
for i in list1:
  print (list1[i]*2)
[ ]

In [ ]:
x = 'This is a string'
print(x[0])

In [ ]:
print(x[0:1]) #prints starting from index and stops before 1

In [ ]:
print(x[-2])

In [ ]:
print(x[-4:-2])

In [ ]:
print(x[-8:-3])

In [ ]:
x[:3]

In [ ]:
x[3:]

In [ ]:
firstname = 'MSIS'
lastname = "Manipal"

In [ ]:
print(firstname + lastname)

In [ ]:
print(firstname *3)

In [ ]:
print('is' in firstname) #case sensitive

In [ ]:
print('IS' in firstname)

In [ ]:
firstname = "Jim Duncan Halpert".split(' ')[0]
middlename = "Jim Duncan Halpert".split(' ')[1]
lastname = "Jim Duncan Halpert".split(' ')[-1]

In [ ]:
print(firstname)
print(middlename)
print(lastname)

In [ ]:
'Michael' +17

In [ ]:
'Michael' + '44'

In [ ]:
'Michael' +str(44)

DICTIONARIES

In [ ]:
#dictionaries
x={'tom':'tom.m@gmail.com', 'bill gates':'bill.g@microsoft.com'}

In [ ]:
x['bill gates']

In [ ]:
x[bill.g@microsoft.com]

In [ ]:
x['thomas'] = 'mit@edu.in'

In [ ]:
x

In [ ]:
s ={'store1':'chips','store2':'juice','store3':'noodles'}

In [ ]:
s

In [ ]:
#iterate over all of the keys
for name in x:
    print(name)

In [ ]:
for name in x:
  print(x[name])

In [ ]:
for email in x.values():
  print(email)

In [ ]:
for name in x.items():
  print(name)

In [ ]:
for name, email in x.items():
  print(name)
  print(email)

In [ ]:
for name, email in x.items():
  print(name , email)

In [ ]:
x=('tom','micheal','tom.m@gmail.com', 'arizona')
fname,lname,email,place=x
lname

In [ ]:
fname+" 's mail is "+email

In [ ]:
place

In [ ]:
#convinient string formatting
sales_record ={
    'price':3.42,
    'num_items':4,
    'person':'tom',
    'email':'tom.m@gmail.com'
}

In [ ]:
sales_statement='{} bought {} item(s) at a price of {} each for a total of {}'
print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))

In [ ]:
info={
    'name':'robot',
    'dept':'robotics',
    'college':'MSIS'
}

In [ ]:

info_template='{} is from {} department in {} college'
print(info_template.format(info['name'],info['dept'],info['college']))

In [ ]:
import datetime as dt
import time as tm

In [ ]:
tm.time()

#time returns the current time in seconds since the first epoch - jan 1st 1970

In [ ]:
from datetime import time
from datetime import date
from datetime import datetime

In [ ]:
today = date.today()
print('today date is',today)

In [ ]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

In [ ]:
dtnow.year,dtnow.month

In [ ]:
delta = dt.timedelta(days = 100)

In [ ]:
date_before_100_days = today - delta
print( date_before_100_days)

In [ ]:
today> today - delta

In [ ]:
#class in python
class person:
  institute ='manipal school of information sciences'

  def set_name(self,new_name):
    self.name=new_name
  def set_location(self,new_location):
    self.location=new_location

In [ ]:
person=person()
person.set_name('tom')
person.set_location('manipal,udupi,karnataka')

In [ ]:
person_format= '{} works in {}'.format(person.name,person.location)
print(person_format)

In [ ]:
#unordered set
y={'eighty six','x',2,'y',3}
z={1,'x','two','y','a'}
print(y,z)

In [ ]:
y.add(4)
z.add('a')

In [ ]:
print(y,z)

In [ ]:
#mapping the min function between the three list

store1 = [10.00, 12.00, 13.67, 1.37]
store2 = [19.00, 10.10, 12.34, 5.01]
store3 = [15.00, 12.00, 11.00, 6.00]
cheapest = map(min, store1, store2, store3)
costly = map(max,store1 , store2 , store3)
print(cheapest)

In [ ]:
for item in cheapest:
  print (item)

In [ ]:
def calculatesqaure(n):
  return n*n

In [ ]:
numbers=(1,2,3,4)
result = map(calculatesqaure, numbers)
print(result)

In [ ]:
res = list(result)
print(res)

In [ ]:
numbers = (1,2,3,4)

result = map(lambda x:x*x, numbers)
print(result)

In [ ]:
list(result)

In [ ]:
num1= [4,5,6]
num2= [5,6,7]

In [ ]:
result = map(lambda n1, n2: n1+n2, num1, num2)
list(result)

In [ ]:
people = ['python programming langauge', 'computer lab test','vinod scored A','kumar failed']
def split_titale_and_name(person):
  title = person.split()[0]
  lastname = person.split()[-1]
  return '{} {}'.format(title,lastname)

list(map(split_titale_and_name, people))

In [ ]:
#lets iterate from 0 to 200 ad return the odd numbers
odd_numbers = []
for i in range(201):
  if i % 2 != 0:
    odd_numbers.append(i)
print(odd_numbers)

In [ ]:
# write code using lambda function that takes in three paramatersand adds the
# first two

add_first_two = lambda x, y, z: x + y

# Demonstrate the lambda function
result = add_first_two(5, 10, 15)
print(f"Result of adding the 1st 2 parameters: {result}")

result_2 = add_first_two(1, 2, 3)
print(f"Result of adding the 1st 2 parameters: {result_2}")

In [ ]:
#program to double each item in a list using map()
my_list = [1,2,3,4,5]
doubled_list = list(map(lambda x: x*2, my_list))
print(doubled_list)

In [ ]:
#example of lambda that takes in three parameters and adds the first two.
#lambda arguments:expression
#program to show

In [ ]:
#implementation of the quick sort algorithm in python [3,6,8,10,1,2,1]

def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    else:
        pivot = arr[len(arr) // 2]
        left = [x for x in arr if x < pivot]
        middle = [x for x in arr if x == pivot]
        right = [x for x in arr if x > pivot]
        return quick_sort(left) + middle + quick_sort(right)

my_list_to_sort = [3, 6, 8, 10, 1, 2, 1]
sorted_list = quick_sort(my_list_to_sort)
print(f"Original : {my_list_to_sort}")
print(f"Sorted : {sorted_list}")

In [ ]:
#computes square numbers using mapping function/lambda function
def calculatesquare(n):
  return n*n
numbers=(1,2,3,4)
result = map(calculatesquare, numbers)
print(result)
res=list(result)
print(res)

Examples using NUMPY

In [ ]:
import numpy as np

In [ ]:
mylist = [1,2,3]
x = np.array(mylist)
x

In [ ]:
y= np.array([4,5,6])
y

NameError: name 'np' is not defined

In [ ]:
m = np.array([[7,8,9],
             [10,11,12]])
m

In [ ]:
m.shape

In [ ]:
n = np.arange(0,30,2)
n

In [ ]:
import numpy as np
n = np.arange(0,30,2)
n = n.reshape(3,5)
n

In [ ]:
lspace = np.linspace(0,10,9)
lspace

In [ ]:
lspace.resize(3,3)
lspace

In [ ]:
np.ones((5,4))

In [ ]:
np.zeros((2,3))

In [ ]:
np.eye(4)

In [ ]:
num = np.matrix([[11,121,130],[613,34,13],[514,50,16]])
num

In [ ]:
type(num)

In [ ]:
print("main diagonal elements :\n",np.diag(num))

In [ ]:
print("diagonal elements above the main diagonal:",np.diag(num,1))

In [ ]:
print("diagonal elements below the main diagonal:",np.diag(num,-1))

In [ ]:
print("diagonal elements above the main diagonal:",np.diag(num,2))

In [ ]:
print("diagonal elements below the main diagonal:",np.diag(num,-2))

In [ ]:
np.array([1,2,3]*3)

In [ ]:
np.repeat([1,2,3],3)

In [ ]:
p = np.ones([3,3],int)
p

In [ ]:
np.vstack([p,2*p])

In [ ]:
np.vstack([p,2*p,3*p])

In [ ]:
np.hstack([p,2*p])

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x)
print(y)

In [ ]:
print(x+y) #elementwise addition

In [ ]:
print(x-y) #elementwise subtraction

In [ ]:
print(x*y) #elementwise multiplication

In [ ]:
print(x@y) #

In [ ]:
print(x/y) #elementwise divison

In [ ]:
print(x**y) #elementwise power

In [ ]:
x.dot(y) #dot product

In [ ]:
z = np.array([y,y**2])
z

In [ ]:
print(len(z))

In [ ]:
z.shape

In [ ]:
z.T #transpose

In [ ]:
z.T.shape #no. of rows has swapped with no. of columns

In [ ]:
z.dtype

In [ ]:
z = z.astype('f') #to cast to a specific type
z.dtype

In [ ]:
a = np.array([-4,-2,1,3,5]) #math functions
a.sum()

In [ ]:
a.max()

In [ ]:
a.min()

In [ ]:
a.mean()

In [ ]:
a.std()

In [ ]:
#argmin and argmax return the index of the maximum and minimum values in the array
a.argmax()

In [ ]:
a.argmin()

In [ ]:
import numpy as np
s = np.arange(100)
s

In [ ]:
s.resize(10,10)
s

In [ ]:
s = np.arange(6)**2
s

In [ ]:
s[0],s[4],s[-1]

In [ ]:
s[1:5] #[start:stop]

In [ ]:
s = np.arange(13)**2
s

In [ ]:
s[-4:]

In [ ]:
s[-5::-2]

In [ ]:
s[-5:-2]

In [ ]:
r = np.arange(100)
r.resize((10,10))
r

In [ ]:
r[3,4] #to slice: array[row,column]

In [ ]:
r[2,1:4]

In [ ]:
r[3,3:6]# use : to selct a range of rows or columns

In [ ]:
r[:3,:-1]

In [ ]:
r[-1,::2]  #this is a slice of the last row , and only every other element

NameError: name 'r' is not defined

In [ ]:
# conditional indexing
r[r>30]

In [ ]:
r[r<30]

In [ ]:
r[r>30]=30
r

In [ ]:
r2 = r[:3,:3]
r2

In [ ]:
r2[:] = 0
r2

In [ ]:
r

In [ ]:
r_copy = r.copy()
r_copy

In [ ]:

[ ]

print(r_copy, '\n')
print(r)

In [ ]:
#iteratring over arrays
test = np.random.randint(0,10,(4,3))
test

In [ ]:
for row in test:
  print(row)

In [ ]:
for i in range(len(test)):
  print(test[i])

In [ ]:
for i , row in enumerate(test): #iterate by row and index:
  print('row',i,'is',row)

In [ ]:
#use zip to iterate over multiple iterables
test2 = test**2
test2

In [ ]:
for i,j in zip(test,test2):
  print(i,'+',j,'=',i+j)

In [ ]:
#axis =0 -> column wise operation
#axis = 1 -> row wise operations

In [ ]:
marks = np.array([
    [80,90,97],
    [65,70,72],
    [88,92,85],
    [55,60,58]
])
student_total = np.sum(marks,axis=1)
print("total of each student:",student_total)

student_average = np.mean(marks,axis=1)
print("average of each student:",student_average)

subject_total = np.sum(marks,axis=0)
print("total of each subject:",subject_total)

subject_average = np.mean(marks,axis=0)
print("average of each subject:",subject_average)

In [ ]:
marks = np.array([
    [80,90,97],
    [65,70,72],
    [88,92,85],
    [55,60,58]
])
student_total = np.sum(marks,axis=1)
print("total of each student:",student_total)

student_average = np.mean(marks,axis=1)
print("average of each student:",student_average)

subject_total = np.sum(marks,axis=0)
print("total of each subject:",subject_total)

subject_average = np.mean(marks,axis=0)
print("average of each subject:",subject_average)

ASSIGNMENT

In [ ]:
#1. # Create a constant array
constant_array = np.full((2, 2), 7.0)
print(constant_array)

In [ ]:
#2. # Create an array filled with random values
random_array = np.random.rand(2, 2)
print(random_array)

In [ ]:
#3. Create a NumPy array containing the numbers from 10 to 50. Display:
#The array
#Number of elements
#Shape
#Dimension
#Data type

array = np.arange(10, 51)
print("Array:", array)
print("Number of elements:", len(array))
print("shape:", array.shape)
print("Dimension:", array.ndim)
print("Data type:",array.dtype)

In [ ]:
#Using NumPy, create:
#A 1D array containing 10 zeros
#A 3 × 3 array containing ones
#A 4 × 4 identity matrix
#An array containing numbers from 5 to 50 with a step size of 5.

In [ ]:
# A 1D array containing 10 zeros
array_zeros = np.zeros(10)
print("1D array of 10 zeros:", array_zeros)
print("1D array of 10 zeros:", array_zeros.astype(int))

In [ ]:
# A 3 x 3 array containing ones
array_ones = np.ones((3, 3))
print("\n3x3 array of ones:\n", array_ones)
print("\n3x3 array of ones:\n", array_ones.astype(int))

In [ ]:
# A 4 x 4 identity matrix
identity_matrix = np.eye(4)
print("\n4x4 identity matrix:\n", identity_matrix)
print("\n4x4 identity matrix:\n", identity_matrix.astype(int))

In [ ]:
# An array containing numbers from 5 to 50 with a step size of 5
array_step = np.arange(5, 51, 5)
print("\nArray from 5 to 50 with step 5:", array_step)

In [ ]:
#5.
#Create an array containing numbers from 1 to 24. Reshape it into:
#4 × 6
#6 × 4
#2 × 3 × 4
#Display the shape and ndim of each result.


initial_array = np.arange(1,25)
print("Initial array:", initial_array)
print("Shape of initial array:", initial_array.shape)
print("Dimension of initial array:", initial_array.ndim)


reshape4x6 = initial_array.reshape(4, 6)
print("\nReshaped to 4x6 array:\n", reshape4x6)
print("Shape:", reshape4x6.shape)
print("Dimension:", reshape4x6.ndim)


reshape6x4 = initial_array.reshape(6, 4)
print("\nReshaped to 6x4 array:\n", reshape6x4)
print("Shape:", reshape6x4.shape)
print("Dimension:", reshape6x4.ndim)


reshape2x3x4 = initial_array.reshape(2, 3, 4)
print("\nReshaped to 2x3x4 array:\n", reshape2x3x4)
print("Shape:", reshape2x3x4.shape)
print("Dimension:", reshape2x3x4.ndim)

In [ ]:
#Consider: marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])
#Write NumPy statements to display:
marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])

print("Original array:\n", marks)

# First element
print("\nFirst element:", marks[0])

# Last element
print("\nLast element:", marks[-1])

# Third element
print("\nThird element:", marks[2])

# First four elements
print("\nFirst four elements:", marks[:4])

# Last three elements
print("\nLast three elements:", marks[-3:])

In [ ]:
#Create:
#a = np.array([10, 20, 30, 40, 50])
#b = np.array([5, 10, 15, 20, 25])
#Calculate:
#a + b
#a - b
#a * b
#a / b
#Square of every element in a


a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])

print("sum:",a+b)
print("subtraction:",a-b)
print("multiplication:",a*b)
print("division:",a/b)
print("square of elements:",a**2)

In [ ]:
#8. Given:
salary = np.array([25000, 32000, 28000, 45000,
                  50000, 38000, 42000, 30000])
#Find:
#Total salary
total_salary = np.sum(salary)
print("Total salary:", total_salary)

#Average salary
average_salary = np.mean(salary)
print("Average salary:", average_salary)

#Highest salary
highest_salary = np.max(salary)
print("Highest salary:", highest_salary)

#Lowest salary
lowest_salary = np.min(salary)
print("Lowest salary:", lowest_salary)

#Median salary
median_salary = np.median(salary)
print("Median salary:", median_salary)

#Standard deviation
std_dev_salary = np.std(salary)
print("Standard deviation of salary:", std_dev_salary)

In [ ]:
import numpy as np
#9.
#Do not use a Python for loop.
#Given:
marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])
print("Original marks array:\n", marks)

#Using NumPy boolean indexing, find:
#Marks greater than 75
marks_gt_75 = marks[marks > 75]
print("\nMarks greater than 75:", marks_gt_75)

#Marks between 50 and 80
marks_between_50_and_80 = marks[(marks >= 50) & (marks <= 80)]
print("\nMarks between 50 and 80:", marks_between_50_and_80)

#Number of students who scored below 50
students_below_50 = marks[marks < 50]
num_students_below_50 = len(students_below_50)
print("\nNumber of students who scored below 50:", num_students_below_50)

#Percentage of students who scored 60 or above
students_60_or_above = marks[marks >= 60]
percentage_60_or_above = (len(students_60_or_above) / len(marks)) * 100
print("\nPercentage of students who scored 60 or above: {:.2f}%".format(percentage_60_or_above))

In [ ]:
import numpy as np

#10. The following array contains marks of four students in three subjects:
marks = np.array([
   [80, 75, 90],
   [65, 70, 72],
   [88, 92, 85],
   [55, 60, 58]
])

print("Original marks array:\n", marks)

# Calculate:
# Total marks of each student
total_per_student = np.sum(marks, axis=1)
print("\nTotal marks:", total_per_student)

# Average marks of each student
average_per_student = np.mean(marks, axis=1)
print("\nAverage marks:", average_per_student)

# Average marks in each subject
average_per_subject = np.mean(marks, axis=0)
print("\nAverage marks in each subject:", average_per_subject)

# Student with the highest total
highest_total_student_index = np.argmax(total_per_student)
highest_total_student_marks = marks[highest_total_student_index]
print("\nStudent with the highest total marks (index {}): {}".format(highest_total_student_index, highest_total_student_marks))
print("Highest total marks:", total_per_student[highest_total_student_index])

# Highest mark in each subject.
highest_mark_in_each_subject = np.max(marks, axis=0)
print("\nHighest mark in each subject:", highest_mark_in_each_subject)

In [ ]:
import numpy as np

#11. Create:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

#Perform:
# Matrix addition
matrix_addition = A + B
print("\nMatrix Addition (A + B):\n", matrix_addition)

# Element-wise multiplication
elementwise_multiplication = A * B
print("\nElement-wise Multiplication (A * B):\n", elementwise_multiplication)

# Matrix multiplication
matrix_multiplication = A @ B
print("\nMatrix Multiplication (A @ B):\n", matrix_multiplication)

# Transpose of A
transpose_A = A.T
print("\nTranspose of A:\n", transpose_A)

# Explain the difference between: A * B and A @ B
print("\nExplanation of A * B vs A @ B:")
print("A * B performs element-wise multiplication, meaning each element of A is multiplied by the corresponding element of B.")
print("A @ B performs matrix multiplication (dot product). This operation follows the rules of linear algebra")

In [ ]:
import numpy as np

# 12. Daily temperatures for two weeks are:

temperature = np.array([
    31, 32, 33, 35, 36, 34, 32,
    30, 29, 31, 33, 35, 37, 36
])

print("Daily temperatures:\n", temperature)

# Find:]
# Mean temperature
mean_temp = np.mean(temperature)
print("\nMean temperature: {:.2f}°C".format(mean_temp))

# Maximum and minimum temperatures
max_temp = np.max(temperature)
min_temp = np.min(temperature)
print("Maximum temperature: {}°C".format(max_temp))
print("Minimum temperature: {}°C".format(min_temp))

# Number of days above the average temperature
days_above_average = np.sum(temperature > mean_temp)
print("Number of days above the average temperature: {}".format(days_above_average))

# Temperatures greater than 34°C
temps_gt_34 = temperature[temperature > 34]
print("Temperatures greater than 34°C: {}".format(temps_gt_34))

# Difference between maximum and minimum
diff_max_min = max_temp - min_temp
print("Difference between maximum and minimum temperature: {}°C".format(diff_max_min))

# Standard deviation
std_dev_temp = np.std(temperature)
print("Standard deviation of temperature: {:.2f}°C".format(std_dev_temp))

In [ ]:
#13. Monthly sales of a company are:
#sales = np.array([
#    12000, 15000, 17000, 14000,
#    18000, 21000, 19000, 22000,
#    25000, 23000, 26000, 28000
#])

#Determine:
#Total annual sales
#Average monthly sales
#Month with the highest sales
#Month with the lowest sales
#Number of months with sales above ₹20,000
#Percentage increase from January to December
#Hint: Remember that NumPy indexing starts at 0, while month numbering normally starts at 1.


import numpy as np

sales = np.array([
    12000, 15000, 17000, 14000,
    18000, 21000, 19000, 22000,
    25000, 23000, 26000, 28000
])

print("Monthly Sales:\n", sales)

# Total annual sales
total_annual_sales = np.sum(sales)
print("\nTotal annual sales: ₹{:,.2f}".format(total_annual_sales))

# Average monthly sales
average_monthly_sales = np.mean(sales)
print("Average monthly sales: ₹{:,.2f}".format(average_monthly_sales))

# Month with the highest sales
highest_sales_month_index = np.argmax(sales)
highest_sales_value = sales[highest_sales_month_index]
# Add 1 to index to get the actual month number (1-indexed)
print("Month with the highest sales: Month {} (₹{:,.2f})".format(highest_sales_month_index + 1, highest_sales_value))

# Month with the lowest sales
lowest_sales_month_index = np.argmin(sales)
lowest_sales_value = sales[lowest_sales_month_index]
# Add 1 to index to get the actual month number (1-indexed)
print("Month with the lowest sales: Month {} (₹{:,.2f})".format(lowest_sales_month_index + 1, lowest_sales_value))

# Number of months with sales above ₹20,000
months_above_20k = np.sum(sales > 20000)
print("Number of months with sales above ₹20,000: {}".format(months_above_20k))

# Percentage increase from January to December
january_sales = sales[0]
december_sales = sales[-1]

if january_sales != 0:
    percentage_increase = ((december_sales - january_sales) / january_sales) * 100
    print("Percentage increase from January to December: {:.2f}%".format(percentage_increase))
else:
    print("Cannot calculate percentage increase from January to December (January sales are zero).")

Monthly Sales:
 [12000 15000 17000 14000 18000 21000 19000 22000 25000 23000 26000 28000]

Total annual sales: ₹240,000.00
Average monthly sales: ₹20,000.00
Month with the highest sales: Month 12 (₹28,000.00)
Month with the lowest sales: Month 1 (₹12,000.00)
Number of months with sales above ₹20,000: 6
Percentage increase from January to December: 133.33%

In [ ]:
#14. Consider marks of five students in four subjects:
marks = np.array([
    [78, 85, 90, 88],
   [65, 70, 72, 68],
    [92, 88, 95, 91],
   [55, 60, 58, 62],
   [80, 75, 82, 79]
])
#Write a NumPy program that calculates:
#Total marks of every student
total_marks_student = np.sum(marks, axis=1)
print("\nTotal marks of each student:", total_marks_student)

#Average of every student
average_marks_student = np.mean(marks, axis=1)
print("Average marks of each student:", average_marks_student)

#Average mark for every subject
average_marks_subject = np.mean(marks, axis=0)
print("Average mark for each subject:", average_marks_subject)

#Highest-scoring student
highest_scoring_student_index = np.argmax(total_marks_student)
highest_scoring_student_total = total_marks_student[highest_scoring_student_index]
print("\nHighest-scoring student (index {} with total marks {}): Marks: {}".format(highest_scoring_student_index, highest_scoring_student_total, marks[highest_scoring_student_index]))


#Lowest-scoring student
lowest_scoring_student_index = np.argmin(total_marks_student)
lowest_scoring_student_total = total_marks_student[lowest_scoring_student_index]
print("Lowest-scoring student (index {} with total marks {}): Marks: {}".format(lowest_scoring_student_index, lowest_scoring_student_total, marks[lowest_scoring_student_index]))

#Students whose average is greater than 80
students_avg_gt_80_indices = np.where(average_marks_student > 80)[0]
students_avg_gt_80_marks = marks[students_avg_gt_80_indices]
print("\nStudents whose average is greater than 80 (indices {}):\n{}".format(students_avg_gt_80_indices, students_avg_gt_80_marks))

#Overall class average
overall_class_average = np.mean(marks)
print("\nOverall class average: {:.2f}".format(overall_class_average))
#Then assign a performance category based on average:

#|  Average | Category          |
#| -------: | ----------------- |
#|     \u2265 85 | Excellent         |
#| 70–84.99 | Good              |
#| 50–69.99 | Average           |
#|     < 50 | Needs Improvement |
#Challenge: Try assigning these categories using np.where() or np.select() instead of a Python loop.


import numpy as np

marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]
])

print("Original marks array:\n", marks)

Total marks of each student: [341 275 366 235 316]
Average marks of each student: [85.25 68.75 91.5  58.75 79.  ]
Average mark for each subject: [74.  75.6 79.4 77.6]

Highest-scoring student (index 2 with total marks 366): Marks: [92 88 95 91]
Lowest-scoring student (index 3 with total marks 235): Marks: [55 60 58 62]

Students whose average is greater than 80 (indices [0 2]):
[[78 85 90 88]
 [92 88 95 91]]

Overall class average: 76.65
Original marks array:
 [[78 85 90 88]
 [65 70 72 68]
 [92 88 95 91]
 [55 60 58 62]
 [80 75 82 79]]

In [ ]:
#15. Generate 20 random integers between 1 and 100.
import numpy as np

random_integers = np.random.randint(1, 101, 20)
print("20 random integers between 1 and 100:", random_integers)

20 random integers between 1 and 100: [11 35 38 58 43  1 62 43 64 28 63 30  7 54 89  7  2 96 33 83]

In [ ]:
#16. Find all even numbers from the generated array.
even_numbers = random_integers[random_integers % 2 == 0]
print("Even numbers from the array:", even_numbers)

Even numbers from the array: [38 58 62 64 28 30 54  2 96]

In [ ]:
#17. Replace values below 50 with 0.
random_integers[random_integers < 50] = 0
print("Array after replacing values below 50 with 0:", random_integers)

Array after replacing values below 50 with 0: [ 0  0  0 58  0  0 62  0 64  0 63  0  0 54 89  0  0 96  0 83]

In [ ]:
#18. Sort the array in ascending and descending order.
sorted_ascending = np.sort(random_integers)
print("Array sorted in ascending order:", sorted_ascending)

sorted_descending = sorted_ascending[::-1]
print("Array sorted in descending order:", sorted_descending)

Array sorted in ascending order: [ 0  0  0  0  0  0  0  0  0  0  0  0 54 58 62 63 64 83 89 96]
Array sorted in descending order: [96 89 83 64 63 62 58 54  0  0  0  0  0  0  0  0  0  0  0  0]

In [ ]:
#19. Find unique values and their frequencies.
unique_values, counts = np.unique(random_integers, return_counts=True)
print("Unique values:", unique_values)
print("Frequencies:", counts)

Unique values: [ 0 54 58 62 63 64 83 89 96]
Frequencies: [12  1  1  1  1  1  1  1  1]

In [ ]:
#20. Create a 5 × 5 random matrix and calculate row-wise and column-wise means.
random_matrix = np.random.randint(0, 100, size=(5, 5))
print("5x5 Random Matrix:\n", random_matrix)

row_wise_mean = np.mean(random_matrix, axis=1)
print("\nRow-wise Means:", row_wise_mean)

col_wise_mean = np.mean(random_matrix, axis=0)
print("Column-wise Means:", col_wise_mean)

5x5 Random Matrix:
 [[33 64 46 84  4]
 [37 82 70 98 33]
 [ 2 81 29 40 98]
 [35 59 39 79 82]
 [81 29 90 96 79]]

Row-wise Means: [46.2 64.  50.  58.8 75. ]
Column-wise Means: [37.6 63.  54.8 79.4 59.2]

In [ ]:
#21. Take your own example to normalize an array.
# Min-Max Normalization: (x - min(x)) / (max(x) - min(x))

my_array_to_normalize = np.array([10, 20, 30, 40, 50, 100])
print("Original array for normalization:", my_array_to_normalize)

min_val = np.min(my_array_to_normalize)
max_val = np.max(my_array_to_normalize)

normalized_array = (my_array_to_normalize - min_val) / (max_val - min_val)
print("Normalized array:", normalized_array)

Original array for normalization: [ 10  20  30  40  50 100]
Normalized array: [0.         0.11111111 0.22222222 0.33333333 0.44444444 1.        ]

In [ ]:
#22. Use your own data to standardize an array.
# Standardization: (x - mean(x)) / std(x)

my_array_to_standardize = np.array([5, 10, 15, 20, 25, 30])
print("Original array for standardization:", my_array_to_standardize)

mean_val = np.mean(my_array_to_standardize)
std_dev = np.std(my_array_to_standardize)

standardized_array = (my_array_to_standardize - mean_val) / std_dev
print("Standardized array:", standardized_array)

Original array for standardization: [ 5 10 15 20 25 30]
Standardized array: [-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]

In [ ]:
#23. Create a NumPy array containing 100 random exam marks and determine how many students fall into the ranges 0–39, 40–59, 60–79, and 80–100.
exam_marks = np.random.randint(0, 101, 100)
print("100 Random Exam Marks:\n", exam_marks)

# Count students in each range
range_0_39 = np.sum((exam_marks >= 0) & (exam_marks <= 39))
range_40_59 = np.sum((exam_marks >= 40) & (exam_marks <= 59))
range_60_79 = np.sum((exam_marks >= 60) & (exam_marks <= 79))
range_80_100 = np.sum((exam_marks >= 80) & (exam_marks <= 100))

print("\nNumber of students in range 0-39:", range_0_39)
print("Number of students in range 40-59:", range_40_59)
print("Number of students in range 60-79:", range_60_79)
print("Number of students in range 80-100:", range_80_100)

100 Random Exam Marks:
 [ 6 39 70 43  7 11 48 94 53 36 97 14 21 32 55 11 30 81 34 48 52 46 92 11
 14 19 39 30  3 65 17 85 98 87 63 99 57 30  5 96 59 84 61 49 81  4 12 35
 55 84 60 55 79 77 36 41  0 39 67 50 36 67 91 25 40 89 39 75 48 55 28 97
 89  7 98 96 91 40 95 48 80 40 13 31 22 98 93 86 54 86 73 51 28 68 38 39
 37 64 58 42]

Number of students in range 0-39: 38
Number of students in range 40-59: 24
Number of students in range 60-79: 13
Number of students in range 80-100: 25

In [ ]:
#24. Compare the time required to multiply 1,000,000 numbers using a Python list and a NumPy array.
import time

SIZE = 1_000_000

# Python list multiplication
python_list1 = list(range(SIZE))
python_list2 = list(range(SIZE))

start_time = time.time()
python_result = [a * b for a, b in zip(python_list1, python_list2)]
end_time = time.time()
python_time = end_time - start_time
print(f"Time taken for Python list multiplication: {python_time:.6f} seconds")

# NumPy array multiplication
numpy_array1 = np.arange(SIZE)
numpy_array2 = np.arange(SIZE)

start_time = time.time()
numpy_result = numpy_array1 * numpy_array2
end_time = time.time()
numpy_time = end_time - start_time
print(f"Time taken for NumPy array multiplication: {numpy_time:.6f} seconds")

print(f"\nNumPy is approximately {python_time / numpy_time:.2f} times faster than Python lists for this operation.")

Time taken for Python list multiplication: 0.188123 seconds
Time taken for NumPy array multiplication: 0.007050 seconds

NumPy is approximately 26.68 times faster than Python lists for this operation.

DATA PREPROCESSING

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
data = pd.read_csv("drive/My Drive/Colab Notebooks/datasets/Data.csv")
dataset = data
data

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
x= dataset.iloc[:,:-1].values #for independent values

In [ ]:
dataset.dtypes

Country       object
Age          float64
Salary       float64
Purchased     object
dtype: object

In [ ]:
dataset.shape

(10, 4)

In [ ]:
dataset.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [ ]:
dataset.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     object
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes

In [ ]:
dataset.tail()

   Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
dataset.describe()

             Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [ ]:
dataset.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [ ]:
dataset.duplicated().sum()

np.int64(0)

In [ ]:
dataset
X = dataset.iloc[:,:-1].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
y = dataset.iloc[:,3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [ ]:
#taking care of missing data
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer = imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
#encoding categorical data
#encoding the independent variables
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x = LabelEncoder()
x[:,0] = labelencoder_x.fit_transform(x[:,0])
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, nan],
       [0, 35.0, 58000.0],
       [2, nan, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [ ]:
#encoding the independent variables
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[("country", OneHotEncoder(), [0])], remainder="passthrough")
x = ct.fit_transform(X)
x
x.astype(int)

array([[    1,     0,     0,    44, 72000],
       [    0,     0,     1,    27, 48000],
       [    0,     1,     0,    30, 54000],
       [    0,     0,     1,    38, 61000],
       [    0,     1,     0,    40, 63777],
       [    1,     0,     0,    35, 58000],
       [    0,     0,     1,    38, 52000],
       [    1,     0,     0,    48, 79000],
       [    0,     1,     0,    50, 83000],
       [    1,     0,     0,    37, 67000]])

In [ ]:
#encoding the dependent variable
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
#split data into Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state= 45)

In [ ]:

X_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778]], dtype=object)

In [ ]:
#feature scaling
#sc_x = (X[1]-mean)/standard Deviation
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=45)

sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train)
X_test = sc_x.transform(X_test)
X_test

array([[-1.        ,  2.64575131, -0.77459667, -1.39625191, -0.93979342],
       [-1.        ,  2.64575131, -0.77459667,  0.03989291, -0.10442149]])

In [ ]:
X_train

array([[-1.        , -0.37796447,  1.29099445, -1.82709535, -1.45240802],
       [-1.        ,  2.64575131, -0.77459667,  1.47603773,  1.53784378],
       [ 1.        , -0.37796447, -0.77459667, -0.39095053,  0.17087153],
       [-1.        , -0.37796447,  1.29099445, -0.1356359 , -1.11066496],
       [ 1.        , -0.37796447, -0.77459667, -0.6781795 , -0.59805036],
       [ 1.        , -0.37796447, -0.77459667,  1.18880877,  1.19610072],
       [ 1.        , -0.37796447, -0.77459667,  0.61435084,  0.59805036],
       [-1.        , -0.37796447,  1.29099445, -0.24733605, -0.34174306]])

assignment 2

In [ ]:
#1. Create a Pandas Series containing the marks: 78, 85, 92, 67, 88
#Display:
	#Complete Series
	#Values
	#Index
	#Data type
	#Mean
	#Maximum
	#Minimum

import pandas as pd

# Create a Pandas Series
marks_series = pd.Series([78, 85, 92, 67, 88])

# Display Complete Series
print("Complete Series:\n", marks_series)

# Display Values
print("\nValues:\n", marks_series.values)

# Display Index
print("\nIndex:\n", marks_series.index)

# Display Data type
print("\nData type:", marks_series.dtype)

# Display Mean
print("\nMean:", marks_series.mean())

# Display Maximum
print("\nMaximum:", marks_series.max())

# Display Minimum
print("\nMinimum:", marks_series.min())

Complete Series:
 0    78
1    85
2    92
3    67
4    88
dtype: int64

Values:
 [78 85 92 67 88]

Index:
 RangeIndex(start=0, stop=5, step=1)

Data type: int64

Mean: 82.0

Maximum: 92

Minimum: 67

In [ ]:
#2. Create a Series containing:
  #| Student | Marks |
	#| ------- | ----: |
	#| Asha    |    85 |
	#| Ravi    |    78 |
	#| Meena   |    92 |
	#| Kiran   |    74 |
	#| Arun    |    88 |
	#Display the marks of Meena.

import pandas as pd

# Create a dictionary for the Series
student_marks_data = {
    'Asha': 85,
    'Ravi': 78,
    'Meena': 92,
    'Kiran': 74,
    'Arun': 88
}

# Create a Pandas Series from the dictionary
student_marks_series = pd.Series(student_marks_data)

# Display the marks of Meena
print(f"Marks of Meena: {student_marks_series['Meena']}")

Marks of Meena: 92


3. Create the following DataFrame:

| Name  | Age | Department | Marks |
| ----- | --: | ---------- | ----: |
| Asha  |  22 | CSE        |    85 |
| Ravi  |  23 | ECE        |    78 |
| Meena |  21 | CSE        |    92 |
| Kiran |  24 | ME         |    74 |
| Arun  |  22 | ECE        |    88 |

Display:

	Complete DataFrame
	First 3 rows
	Last 2 rows
	Shape
	Column names
	Data types

In [ ]:
import pandas as pd

# Create the DataFrame
students_data = {
    'Name': ['Asha', 'Ravi', 'Meena', 'Kiran', 'Arun'],
    'Age': [22, 23, 21, 24, 22],
    'Department': ['CSE', 'ECE', 'CSE', 'ME', 'ECE'],
    'Marks': [85, 78, 92, 74, 88]
}
df_students = pd.DataFrame(students_data)

# Display Complete DataFrame
print("Complete DataFrame:\n", df_students)

# Display First 3 rows
print("\nFirst 3 rows:\n", df_students.head(3))

# Display Last 2 rows
print("\nLast 2 rows:\n", df_students.tail(2))

# Display Shape
print("\nShape:", df_students.shape)

# Display Column names
print("\nColumn names:", df_students.columns)

# Display Data types
print("\nData types:\n", df_students.dtypes)

Complete DataFrame:
     Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
3  Kiran   24         ME     74
4   Arun   22        ECE     88

First 3 rows:
     Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92

Last 2 rows:
     Name  Age Department  Marks
3  Kiran   24         ME     74
4   Arun   22        ECE     88

Shape: (5, 4)

Column names: Index(['Name', 'Age', 'Department', 'Marks'], dtype='object')

Data types:
 Name          object
Age            int64
Department    object
Marks          int64
dtype: object

4. Using the previous DataFrame, display:

	info()
	describe()
	Number of rows
	Number of columns

In [ ]:
# Display info()
print("\nDataFrame Info:")
df_students.info()

# Display describe()
print("\nDataFrame Description:")
display(df_students.describe())

# Display Number of rows
print(f"\nNumber of rows: {df_students.shape[0]}")

# Display Number of columns
print(f"Number of columns: {df_students.shape[1]}")

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         5 non-null      int64
 2   Department  5 non-null      object
 3   Marks       5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

DataFrame Description:

             Age      Marks
count   5.000000   5.000000
mean   22.400000  83.400000
std     1.140175   7.334848
min    21.000000  74.000000
25%    22.000000  78.000000
50%    22.000000  85.000000
75%    23.000000  88.000000
max    24.000000  92.000000

Number of rows: 5
Number of columns: 4

5. Using df, display:

	Name column
	Marks column
	Name and Marks together

In [ ]:
# Display Name column
print("\nName Column:\n", df_students['Name'])

# Display Marks column
print("\nMarks Column:\n", df_students['Marks'])

# Display Name and Marks together
print("\nName and Marks Columns Together:\n", df_students[['Name', 'Marks']])

Name Column:
 0     Asha
1     Ravi
2    Meena
3    Kiran
4     Arun
Name: Name, dtype: object

Marks Column:
 0    85
1    78
2    92
3    74
4    88
Name: Marks, dtype: int64

Name and Marks Columns Together:
     Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88

6. Display:

	First row using iloc
	Third row using iloc
	Rows 1 to 3
	Name and Marks columns using loc

In [ ]:
# Display First row using iloc
print("\nFirst row (iloc[0]):\n", df_students.iloc[0])

# Display Third row using iloc
print("\nThird row (iloc[2]):\n", df_students.iloc[2])

# Display Rows 1 to 3 (inclusive, i.e., index 1, 2, 3) using iloc
print("\nRows 1 to 3 (iloc[1:4]):\n", df_students.iloc[1:4])

# Display Name and Marks columns using loc
print("\nName and Marks columns (loc[:, ['Name', 'Marks']]):\n", df_students.loc[:, ['Name', 'Marks']])

First row (iloc[0]):
 Name          Asha
Age             22
Department     CSE
Marks           85
Name: 0, dtype: object

Third row (iloc[2]):
 Name          Meena
Age              21
Department      CSE
Marks            92
Name: 2, dtype: object

Rows 1 to 3 (iloc[1:4]):
     Name  Age Department  Marks
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
3  Kiran   24         ME     74

Name and Marks columns (loc[:, ['Name', 'Marks']]):
     Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88

7. Find:

	Students scoring above 80.
	Students scoring between 75 and 90.
	Students belonging to CSE.
	CSE students scoring above 80.

In [ ]:
# Students scoring above 80
students_above_80 = df_students[df_students['Marks'] > 80]
print("\nStudents scoring above 80:\n", students_above_80)

# Students scoring between 75 and 90 (inclusive for 75 and 90)
students_between_75_and_90 = df_students[(df_students['Marks'] >= 75) & (df_students['Marks'] <= 90)]
print("\nStudents scoring between 75 and 90:\n", students_between_75_and_90)

# Students belonging to CSE
students_cse = df_students[df_students['Department'] == 'CSE']
print("\nStudents belonging to CSE:\n", students_cse)

# CSE students scoring above 80
cse_students_above_80 = df_students[(df_students['Department'] == 'CSE') & (df_students['Marks'] > 80)]
print("\nCSE students scoring above 80:\n", cse_students_above_80)

Students scoring above 80:
     Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92
4   Arun   22        ECE     88

Students scoring between 75 and 90:
    Name  Age Department  Marks
0  Asha   22        CSE     85
1  Ravi   23        ECE     78
4  Arun   22        ECE     88

Students belonging to CSE:
     Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92

CSE students scoring above 80:
     Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92

8. Display students belonging to either CSE or ECE.

In [ ]:
students_cse_ece = df_students[(df_students['Department'] == 'CSE') | (df_students['Department'] == 'ECE')]
print("\nStudents belonging to either CSE or ECE:\n", students_cse_ece)

Students belonging to either CSE or ECE:
     Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
4   Arun   22        ECE     88

9. Add a new column called Result. Students scoring 75 or above should receive "Pass", otherwise "Fail".

In [ ]:
import numpy as np

df_students['Result'] = np.where(df_students['Marks'] >= 75, 'Pass', 'Fail')
print("\nDataFrame with 'Result' column:\n", df_students)

DataFrame with 'Result' column:
     Name  Age Department  Marks Result
0   Asha   22        CSE     85   Pass
1   Ravi   23        ECE     78   Pass
2  Meena   21        CSE     92   Pass
3  Kiran   24         ME     74   Fail
4   Arun   22        ECE     88   Pass

10. Assign grades according to:

	| Marks | Grade |
	| ----: | ----- |
	|  ≥ 90 | A     |
	|  ≥ 80 | B     |
	|  ≥ 70 | C     |
	|  < 70 | D     |

In [ ]:
import numpy as np

conditions = [
    (df_students['Marks'] >= 90),
    (df_students['Marks'] >= 80),
    (df_students['Marks'] >= 70),
    (df_students['Marks'] < 70)
]
choices = ['A', 'B', 'C', 'D']

df_students['Grade'] = np.select(conditions, choices, default='D') # Default can be anything, as <70 covers all remaining
print("\nDataFrame with 'Grade' column:\n", df_students)

DataFrame with 'Grade' column:
     Name  Age Department  Marks Result Grade
0   Asha   22        CSE     85   Pass     B
1   Ravi   23        ECE     78   Pass     C
2  Meena   21        CSE     92   Pass     A
3  Kiran   24         ME     74   Fail     C
4   Arun   22        ECE     88   Pass     B


11. Sort students:

	By marks in ascending order.
	By marks in descending order.
	By Department and then Marks.

In [ ]:
# Sort by Marks in ascending order
df_sorted_marks_asc = df_students.sort_values(by='Marks', ascending=True)
print("\nStudents sorted by Marks (Ascending):\n", df_sorted_marks_asc)

# Sort by Marks in descending order
df_sorted_marks_desc = df_students.sort_values(by='Marks', ascending=False)
print("\nStudents sorted by Marks (Descending):\n", df_sorted_marks_desc)

# Sort by Department and then by Marks
df_sorted_dept_marks = df_students.sort_values(by=['Department', 'Marks'], ascending=[True, True])
print("\nStudents sorted by Department and then Marks:\n", df_sorted_dept_marks)

Students sorted by Marks (Ascending):
     Name  Age Department  Marks Result Grade
3  Kiran   24         ME     74   Fail     C
1   Ravi   23        ECE     78   Pass     C
0   Asha   22        CSE     85   Pass     B
4   Arun   22        ECE     88   Pass     B
2  Meena   21        CSE     92   Pass     A

Students sorted by Marks (Descending):
     Name  Age Department  Marks Result Grade
2  Meena   21        CSE     92   Pass     A
4   Arun   22        ECE     88   Pass     B
0   Asha   22        CSE     85   Pass     B
1   Ravi   23        ECE     78   Pass     C
3  Kiran   24         ME     74   Fail     C

Students sorted by Department and then Marks:
     Name  Age Department  Marks Result Grade
0   Asha   22        CSE     85   Pass     B
2  Meena   21        CSE     92   Pass     A
1   Ravi   23        ECE     78   Pass     C
4   Arun   22        ECE     88   Pass     B
3  Kiran   24         ME     74   Fail     C


12. Consider:

data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, np.nan, 24, 22],
    "Marks": [85, np.nan, 92, 74, 88]
}

students = pd.DataFrame(data)

Find:

Missing values
Number of missing values in each column
Rows containing missing values

In [ ]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, np.nan, 24, 22],
    "Marks": [85, np.nan, 92, 74, 88]
}

students = pd.DataFrame(data)
print("Original DataFrame with missing values:\n", students)

# Find missing values
print("\nMissing values (True indicates missing):\n", students.isnull())

# Number of missing values in each column
print("\nNumber of missing values per column:\n", students.isnull().sum())

# Rows containing missing values
print("\nRows containing missing values:\n", students[students.isnull().any(axis=1)])

Original DataFrame with missing values:
     Name   Age  Marks
0   Asha  22.0   85.0
1   Ravi  23.0    NaN
2  Meena   NaN   92.0
3  Kiran  24.0   74.0
4   Arun  22.0   88.0

Missing values (True indicates missing):
     Name    Age  Marks
0  False  False  False
1  False  False   True
2  False   True  False
3  False  False  False
4  False  False  False

Number of missing values per column:
 Name     0
Age      1
Marks    1
dtype: int64

Rows containing missing values:
     Name   Age  Marks
1   Ravi  23.0    NaN
2  Meena   NaN   92.0

13. Replace:

	Missing Age with average Age
	Missing Marks with average Marks

In [ ]:
# Calculate average Age and Marks
average_age = students['Age'].mean()
average_marks = students['Marks'].mean()

# Replace missing Age with average Age
students['Age'].fillna(average_age, inplace=True)

# Replace missing Marks with average Marks
students['Marks'].fillna(average_marks, inplace=True)

print("DataFrame after replacing missing values with column averages:\n", students)

DataFrame after replacing missing values with column averages:
     Name    Age  Marks
0   Asha  22.00  85.00
1   Ravi  23.00  84.75
2  Meena  22.75  92.00
3  Kiran  24.00  74.00
4   Arun  22.00  88.00

/tmp/ipykernel_1961/2264420799.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  students['Age'].fillna(average_age, inplace=True)
/tmp/ipykernel_1961/2264420799.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  students['Marks'].fillna(average_marks, inplace=True)

14. Remove rows containing missing values.

In [ ]:
# Remove rows containing any missing values (if any remain, though they shouldn't after fillna)
# For demonstration, let's create a new DataFrame with some NaNs to show dropna functionality
data_with_more_nan = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun", "Priya"],
    "Age": [22, 23, np.nan, 24, 22, 25],
    "Marks": [85, np.nan, 92, 74, 88, np.nan],
    "Grade": ['A', 'B', 'A', 'C', np.nan, 'B']
}
df_temp = pd.DataFrame(data_with_more_nan)
print("Original DataFrame with more NaNs to demonstrate dropna:\n", df_temp)

df_cleaned = df_temp.dropna()
print("\nDataFrame after removing rows with any missing values:\n", df_cleaned)

Original DataFrame with more NaNs to demonstrate dropna:
     Name   Age  Marks Grade
0   Asha  22.0   85.0     A
1   Ravi  23.0    NaN     B
2  Meena   NaN   92.0     A
3  Kiran  24.0   74.0     C
4   Arun  22.0   88.0   NaN
5  Priya  25.0    NaN     B

DataFrame after removing rows with any missing values:
     Name   Age  Marks Grade
0   Asha  22.0   85.0     A
3  Kiran  24.0   74.0     C

15. Consider:

data = {
    "Name": ["Asha", "Ravi", "Meena", "Asha", "Arun"],
    "Marks": [85, 78, 92, 85, 88]
}

df2 = pd.DataFrame(data)

Find duplicates:
Display duplicate rows:
Remove duplicates:

16. Given:

marks = pd.DataFrame({
    "Student": ["A", "B", "C", "D", "E"],
    "Marks": [78, 85, 92, 67, 88]
})

Calculate:

Mean
Median
Maximum
Minimum
Standard deviation
Sum

17. Consider:

data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE"
    ],

    "Marks": [
        85, 78, 92,
        74, 88, 80
    ]
}

df = pd.DataFrame(data)


Find:
Average marks by department
Maximum marks by department
Number of students in each department

For each department, calculate:
Mean
Minimum
Maximum
Count

18. Create:

students = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Name": ["Asha", "Ravi", "Meena", "Kiran"]
})

marks = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Marks": [85, 78, 92, 74]
})

Combine both DataFrames using StudentID.

19. Use the following dataset:

data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya",
        "John", "Priya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE",
        "ME", "ECE"
    ],

    "Attendance": [
        92, 75, 96, 68,
        82, 88, 72, 95
    ],

    "Internal": [
        85, 72, 94, 65,
        80, 86, 70, 91
    ],

    "FinalMarks": [
        88, 74, 96, 62,
        83, 89, 68, 93
    ]
}

df = pd.DataFrame(data)


Perform the following analysis:

Display the first five records.
Find the dimensions of the dataset.
Find the average final mark.
Find the highest-scoring student.
Find the lowest-scoring student.
Display students scoring above 80.
Find average marks by department.
Find students having attendance above 80%.
Sort students by FinalMarks.
Add a Result column: Pass if FinalMarks ≥ 70, otherwise Fail.
Add a performance category:
	≥90 → Excellent
	≥80 → Very Good
	≥70 → Good
	<70 → Needs Improvement
Find the department having the highest average FinalMarks.

20. Create:

employees = pd.DataFrame({
    "Employee": [
        "E01", "E02", "E03", "E04",
        "E05", "E06", "E07", "E08"
    ],

    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "Finance", "IT", "Finance"
    ],

    "Experience": [
        5, 3, 7, 4,
        6, 8, 2, 5
    ],

    "Salary": [
        60000, 45000, 75000, 65000,
        55000, 85000, 48000, 70000
    ]
})


Determine:

Average salary.
Maximum and minimum salary.
Employee receiving the highest salary.
Employees earning above ₹60,000.
Average salary for each department.
Average experience by department.
Number of employees in each department.
Sort employees by salary.
Find IT employees with more than 3 years of experience.
Add a SalaryLevel column:
	≥ ₹75,000 → High
	₹50,000–₹74,999 → Medium
	< ₹50,000 → Low

### 15. Find duplicates, display duplicate rows, and remove duplicates.

In [1]:
import pandas as pd

data = {
    "Name": ["Asha", "Ravi", "Meena", "Asha", "Arun"],
    "Marks": [85, 78, 92, 85, 88]
}

df2 = pd.DataFrame(data)
print("Original DataFrame:\n", df2)

# Find duplicates
duplicates = df2.duplicated()
print("\nBoolean Series indicating duplicate rows:\n", duplicates)

# Display duplicate rows
duplicate_rows = df2[df2.duplicated()]
print("\nDuplicate rows (based on all columns):\n", duplicate_rows)

# Remove duplicates
df_no_duplicates = df2.drop_duplicates()
print("\nDataFrame after removing duplicates:\n", df_no_duplicates)

Original DataFrame:
     Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3   Asha     85
4   Arun     88

Boolean Series indicating duplicate rows:
 0    False
1    False
2    False
3     True
4    False
dtype: bool

Duplicate rows (based on all columns):
    Name  Marks
3  Asha     85

DataFrame after removing duplicates:
     Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
4   Arun     88

### 16. Calculate: Mean, Median, Maximum, Minimum, Standard deviation, Sum for the given DataFrame.

In [2]:
import pandas as pd
import numpy as np

marks = pd.DataFrame({
    "Student": ["A", "B", "C", "D", "E"],
    "Marks": [78, 85, 92, 67, 88]
})

print("Original Marks DataFrame:\n", marks)

# Calculate statistics for the 'Marks' column
mean_marks = marks['Marks'].mean()
median_marks = marks['Marks'].median()
max_marks = marks['Marks'].max()
min_marks = marks['Marks'].min()
std_dev_marks = marks['Marks'].std()
sum_marks = marks['Marks'].sum()

print(f"\nMean Marks: {mean_marks:.2f}")
print(f"Median Marks: {median_marks:.2f}")
print(f"Maximum Marks: {max_marks}")
print(f"Minimum Marks: {min_marks}")
print(f"Standard Deviation of Marks: {std_dev_marks:.2f}")
print(f"Sum of Marks: {sum_marks}")

Original Marks DataFrame:
   Student  Marks
0       A     78
1       B     85
2       C     92
3       D     67
4       E     88

Mean Marks: 82.00
Median Marks: 85.00
Maximum Marks: 92
Minimum Marks: 67
Standard Deviation of Marks: 9.82
Sum of Marks: 410

### 17. Analyze student data by department: Average marks, maximum marks, number of students, and grouped statistics (Mean, Minimum, Maximum, Count).

In [3]:
import pandas as pd

data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE"
    ],

    "Marks": [
        85, 78, 92,
        74, 88, 80
    ]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# Average marks by department
avg_marks_by_dept = df.groupby('Department')['Marks'].mean()
print("\nAverage marks by Department:\n", avg_marks_by_dept)

# Maximum marks by department
max_marks_by_dept = df.groupby('Department')['Marks'].max()
print("\nMaximum marks by Department:\n", max_marks_by_dept)

# Number of students in each department
students_per_dept = df['Department'].value_counts()
print("\nNumber of students in each Department:\n", students_per_dept)

# For each department, calculate: Mean, Minimum, Maximum, Count
dept_stats = df.groupby('Department')['Marks'].agg(['mean', 'min', 'max', 'count'])
print("\nDepartment-wise Statistics (Mean, Min, Max, Count):\n", dept_stats)

Original DataFrame:
     Name Department  Marks
0   Asha        CSE     85
1   Ravi        ECE     78
2  Meena        CSE     92
3  Kiran         ME     74
4   Arun        ECE     88
5  Divya        CSE     80

Average marks by Department:
 Department
CSE    85.666667
ECE    83.000000
ME     74.000000
Name: Marks, dtype: float64

Maximum marks by Department:
 Department
CSE    92
ECE    88
ME     74
Name: Marks, dtype: int64

Number of students in each Department:
 Department
CSE    3
ECE    2
ME     1
Name: count, dtype: int64

Department-wise Statistics (Mean, Min, Max, Count):
                  mean  min  max  count
Department
CSE         85.666667   80   92      3
ECE         83.000000   78   88      2
ME          74.000000   74   74      1

### 18. Combine two DataFrames using StudentID.

In [4]:
import pandas as pd

students = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Name": ["Asha", "Ravi", "Meena", "Kiran"]
})

marks = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Marks": [85, 78, 92, 74]
})

print("Students DataFrame:\n", students)
print("\nMarks DataFrame:\n", marks)

# Combine both DataFrames using StudentID
combined_df = pd.merge(students, marks, on='StudentID')
print("\nCombined DataFrame:\n", combined_df)

Students DataFrame:
    StudentID   Name
0        101   Asha
1        102   Ravi
2        103  Meena
3        104  Kiran

Marks DataFrame:
    StudentID  Marks
0        101     85
1        102     78
2        103     92
3        104     74

Combined DataFrame:
    StudentID   Name  Marks
0        101   Asha     85
1        102   Ravi     78
2        103  Meena     92
3        104  Kiran     74

### 19. Perform comprehensive analysis on a student dataset, including statistics, filtering, sorting, and adding new categorical columns.

In [5]:
import pandas as pd
import numpy as np

data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya",
        "John", "Priya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE",
        "ME", "ECE"
    ],

    "Attendance": [
        92, 75, 96, 68,
        82, 88, 72, 95
    ],

    "Internal": [
        85, 72, 94, 65,
        80, 86, 70, 91
    ],

    "FinalMarks": [
        88, 74, 96, 62,
        83, 89, 68, 93
    ]
}

df = pd.DataFrame(data)

print("Original Student DataFrame:\n", df)

# Display the first five records.
print("\nFirst five records:\n", df.head(5))

# Find the dimensions of the dataset.
print("\nDimensions of the dataset (rows, columns):", df.shape)

# Find the average final mark.
avg_final_mark = df['FinalMarks'].mean()
print(f"\nAverage Final Mark: {avg_final_mark:.2f}")

# Find the highest-scoring student.
highest_scoring_student = df.loc[df['FinalMarks'].idxmax()]
print("\nHighest-scoring student:\n", highest_scoring_student)

# Find the lowest-scoring student.
lowest_scoring_student = df.loc[df['FinalMarks'].idxmin()]
print("\nLowest-scoring student:\n", lowest_scoring_student)

# Display students scoring above 80.
students_above_80 = df[df['FinalMarks'] > 80]
print("\nStudents scoring above 80 in FinalMarks:\n", students_above_80)

# Find average marks by department.
avg_marks_by_dept = df.groupby('Department')['FinalMarks'].mean()
print("\nAverage Final Marks by Department:\n", avg_marks_by_dept)

# Find students having attendance above 80%.
students_high_attendance = df[df['Attendance'] > 80]
print("\nStudents with Attendance above 80%:\n", students_high_attendance)

# Sort students by FinalMarks.
df_sorted_by_final_marks = df.sort_values(by='FinalMarks', ascending=False)
print("\nStudents sorted by FinalMarks (Descending):\n", df_sorted_by_final_marks)

# Add a Result column: Pass if FinalMarks ≥ 70, otherwise Fail.
df['Result'] = np.where(df['FinalMarks'] >= 70, 'Pass', 'Fail')
print("\nDataFrame with 'Result' column:\n", df)

# Add a performance category:
# ≥90 → Excellent, ≥80 → Very Good, ≥70 → Good, <70 → Needs Improvement
conditions = [
    (df['FinalMarks'] >= 90),
    (df['FinalMarks'] >= 80),
    (df['FinalMarks'] >= 70)
]
choices = ['Excellent', 'Very Good', 'Good']
df['PerformanceCategory'] = np.select(conditions, choices, default='Needs Improvement')
print("\nDataFrame with 'PerformanceCategory' column:\n", df)

# Find the department having the highest average FinalMarks.
department_highest_avg_marks = avg_marks_by_dept.idxmax()
highest_avg_marks_value = avg_marks_by_dept.max()
print(f"\nDepartment with the highest average FinalMarks: {department_highest_avg_marks} (Average: {highest_avg_marks_value:.2f})")

Original Student DataFrame:
     Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
1   Ravi        ECE          75        72          74
2  Meena        CSE          96        94          96
3  Kiran         ME          68        65          62
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
6   John         ME          72        70          68
7  Priya        ECE          95        91          93

First five records:
     Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
1   Ravi        ECE          75        72          74
2  Meena        CSE          96        94          96
3  Kiran         ME          68        65          62
4   Arun        ECE          82        80          83

Dimensions of the dataset (rows, columns): (8, 5)

Average Final Mark: 81.62

Highest-scoring student:
 Name          Meena
Department      CSE
Attendance       96
Internal         94
FinalMarks       96
Name: 2, dtype: object

Lowest-scoring student:
 Name          Kiran
Department       ME
Attendance       68
Internal         65
FinalMarks       62
Name: 3, dtype: object

Students scoring above 80 in FinalMarks:
     Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
2  Meena        CSE          96        94          96
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93

Average Final Marks by Department:
 Department
CSE    91.000000
ECE    83.333333
ME     65.000000
Name: FinalMarks, dtype: float64

Students with Attendance above 80%:
     Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
2  Meena        CSE          96        94          96
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93

Students sorted by FinalMarks (Descending):
     Name Department  Attendance  Internal  FinalMarks
2  Meena        CSE          96        94          96
7  Priya        ECE          95        91          93
5  Divya        CSE          88        86          89
0   Asha        CSE          92        85          88
4   Arun        ECE          82        80          83
1   Ravi        ECE          75        72          74
6   John         ME          72        70          68
3  Kiran         ME          68        65          62

DataFrame with 'Result' column:
     Name Department  Attendance  Internal  FinalMarks Result
0   Asha        CSE          92        85          88   Pass
1   Ravi        ECE          75        72          74   Pass
2  Meena        CSE          96        94          96   Pass
3  Kiran         ME          68        65          62   Fail
4   Arun        ECE          82        80          83   Pass
5  Divya        CSE          88        86          89   Pass
6   John         ME          72        70          68   Fail
7  Priya        ECE          95        91          93   Pass

DataFrame with 'PerformanceCategory' column:
     Name Department  Attendance  Internal  FinalMarks Result  \
0   Asha        CSE          92        85          88   Pass
1   Ravi        ECE          75        72          74   Pass
2  Meena        CSE          96        94          96   Pass
3  Kiran         ME          68        65          62   Fail
4   Arun        ECE          82        80          83   Pass
5  Divya        CSE          88        86          89   Pass
6   John         ME          72        70          68   Fail
7  Priya        ECE          95        91          93   Pass

  PerformanceCategory
0           Very Good
1                Good
2           Excellent
3   Needs Improvement
4           Very Good
5           Very Good
6   Needs Improvement
7           Excellent

Department with the highest average FinalMarks: CSE (Average: 91.00)

### 20. Perform comprehensive analysis on an employee dataset, including statistics, filtering, sorting, and adding new categorical columns.

In [6]:
import pandas as pd
import numpy as np

employees = pd.DataFrame({
    "Employee": [
        "E01", "E02", "E03", "E04",
        "E05", "E06", "E07", "E08"
    ],

    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "Finance", "IT", "Finance"
    ],

    "Experience": [
        5, 3, 7, 4,
        6, 8, 2, 5
    ],

    "Salary": [
        60000, 45000, 75000, 65000,
        55000, 85000, 48000, 70000
    ]
})

print("Original Employees DataFrame:\n", employees)

# Determine Average salary.
avg_salary = employees['Salary'].mean()
print(f"\nAverage Salary: ₹{avg_salary:,.2f}")

# Maximum and minimum salary.
max_salary = employees['Salary'].max()
min_salary = employees['Salary'].min()
print(f"Maximum Salary: ₹{max_salary:,.2f}")
print(f"Minimum Salary: ₹{min_salary:,.2f}")

# Employee receiving the highest salary.
highest_paid_employee = employees.loc[employees['Salary'].idxmax()]
print("\nEmployee receiving the highest salary:\n", highest_paid_employee)

# Employees earning above ₹60,000.
employees_above_60k = employees[employees['Salary'] > 60000]
print("\nEmployees earning above ₹60,000:\n", employees_above_60k)

# Average salary for each department.
avg_salary_by_dept = employees.groupby('Department')['Salary'].mean()
print("\nAverage Salary for each Department:\n", avg_salary_by_dept)

# Average experience by department.
avg_experience_by_dept = employees.groupby('Department')['Experience'].mean()
print("\nAverage Experience by Department:\n", avg_experience_by_dept)

# Number of employees in each department.
employees_per_dept = employees['Department'].value_counts()
print("\nNumber of Employees in each Department:\n", employees_per_dept)

# Sort employees by salary.
employees_sorted_by_salary = employees.sort_values(by='Salary', ascending=False)
print("\nEmployees sorted by Salary (Descending):\n", employees_sorted_by_salary)

# Find IT employees with more than 3 years of experience.
it_employees_experienced = employees[
    (employees['Department'] == 'IT') & (employees['Experience'] > 3)
]
print("\nIT Employees with more than 3 years of experience:\n", it_employees_experienced)

# Add a SalaryLevel column:
# ≥ ₹75,000 → High
# ₹50,000–₹74,999 → Medium
# < ₹50,000 → Low
conditions = [
    (employees['Salary'] >= 75000),
    (employees['Salary'] >= 50000) & (employees['Salary'] < 75000)
]
choices = ['High', 'Medium']
employees['SalaryLevel'] = np.select(conditions, choices, default='Low')
print("\nDataFrame with 'SalaryLevel' column:\n", employees)

Original Employees DataFrame:
   Employee Department  Experience  Salary
0      E01         IT           5   60000
1      E02         HR           3   45000
2      E03         IT           7   75000
3      E04    Finance           4   65000
4      E05         HR           6   55000
5      E06    Finance           8   85000
6      E07         IT           2   48000
7      E08    Finance           5   70000

Average Salary: ₹62,875.00
Maximum Salary: ₹85,000.00
Minimum Salary: ₹45,000.00

Employee receiving the highest salary:
 Employee          E06
Department    Finance
Experience          8
Salary          85000
Name: 5, dtype: object

Employees earning above ₹60,000:
   Employee Department  Experience  Salary
2      E03         IT           7   75000
3      E04    Finance           4   65000
5      E06    Finance           8   85000
7      E08    Finance           5   70000

Average Salary for each Department:
 Department
Finance    73333.333333
HR         50000.000000
IT         61000.000000
Name: Salary, dtype: float64

Average Experience by Department:
 Department
Finance    5.666667
HR         4.500000
IT         4.666667
Name: Experience, dtype: float64

Number of Employees in each Department:
 Department
IT         3
Finance    3
HR         2
Name: count, dtype: int64

Employees sorted by Salary (Descending):
   Employee Department  Experience  Salary
5      E06    Finance           8   85000
2      E03         IT           7   75000
7      E08    Finance           5   70000
3      E04    Finance           4   65000
0      E01         IT           5   60000
4      E05         HR           6   55000
6      E07         IT           2   48000
1      E02         HR           3   45000

IT Employees with more than 3 years of experience:
   Employee Department  Experience  Salary
0      E01         IT           5   60000
2      E03         IT           7   75000

DataFrame with 'SalaryLevel' column:
   Employee Department  Experience  Salary SalaryLevel
0      E01         IT           5   60000      Medium
1      E02         HR           3   45000         Low
2      E03         IT           7   75000        High
3      E04    Finance           4   65000      Medium
4      E05         HR           6   55000      Medium
5      E06    Finance           8   85000        High
6      E07         IT           2   48000         Low
7      E08    Finance           5   70000      Medium